### ISSUE TITLE
Method not found: '!!0 Microsoft.Extensions.AI.IChatClient.GetService(System.Object)'

### ISSUE THREAD

**Issue by jcmag** [tghamm/Mistral.SDK#15]
Hi,

I'm using the Microsoft.Extensions.AI.IChatClient interface in my code (to be able to call ChatGPT, Anthropic, Mistral etc.).
It worked with Mistral.SDK v1.3.1, but after upgrading to v2.0.0 I get this error at runtime :

System.MissingMethodException: Method not found: '!!0 Microsoft.Extensions.AI.IChatClient.GetService(System.Object)'.

Any idea why?

.NET 9.0

**Comment by tghamm** [comment]
Hi, I just added function calling, and was seeing that with Semantic Kernel in testing but thought I had baked in a workaround specifically for this. Can you provide a stripped down example that'll help guide me a bit and narrow it down? That would help a ton, thank you.

**Comment by jcmag** [comment]
Hi,

Here is a sample project that reproduces the exception.
[Bug.zip](https://github.com/user-attachments/files/17997676/Bug.zip)

Actually, the error only occurs when I reference the other packages (Anthropic.SDK and Betalgo.Ranul.OpenAI), so it might be a conflict between the three packages. I have also contacted the owners of the other packages, as the issue may not be with your package.

**Comment by tghamm** [comment]
Thanks for the sample.  I actually wrote Anthropic.SDK as well.  I noted when I removed Betalgo.Ranul.OpenAI, the app seems to run fine.  This does appear to be some sort of version conflict and I note that there are some dependency mismatches between my libraries and theirs, but not related to `IChatClient`...it just has a LOT of dependencies so it's a little tough to tell where exactly the conflict is coming from.  I'll dig a bit further, but you may want to reach out to the author, this isn't related to function calling I don't think, especially since you're not using it in this sample and the issue I saw was only cropping up around that, and fairly certain I resolved it.

**Comment by jcmag** [comment]
ok, thanks for your time! ;)

**Comment by tghamm** [comment]
If you're in a bind: `Microsoft.Extensions.AI.OpenAI` seems to provide a drop-in replacement if you're using the `IChatClient` interface and doesn't produce the error, I just gave it a shot.  Hope it helps and you're more than welcome!
